;YAHYA CAN OZDEMIR 18360859048
;SELECTION SORT ASSEMBLY KODU



org 100h         


MOV BX,0200H                  ;SAYILARIN YERLESTIRILMESI 
MOV BYTE PTR [bx],55h
MOV BYTE PTR [bx+1],66H
MOV BYTE PTR [bx+2],54H
MOV BYTE PTR [bx+3],11H
MOV BYTE PTR [bx+4],87H
MOV BYTE PTR [bx+5],33H
MOV BYTE PTR [bx+6],75H
MOV BYTE PTR [bx+7],05H
MOV BYTE PTR [bx+8],5FH
MOV BYTE PTR [bx+9],23H




MOV BX,0200H    ; SAYILARIN BASLANGIC ADRESI
MOV DI,0        ; CURRENT INDIS DEGERI
MOV SI,0        ; WALKER INDIS DEGERI


J1:            ; DIS DONGUMUZ
MOV DL,[BX+DI] ; DL=EN KUCUK SAYI
MOV SI,DI      ; 
INC SI         ; BU 2 SATIR ILE WALKER = CURRENT+1

J2:            ; IC DONGUMUZ
MOV AL,[BX+SI] ; AL=WALKER
CMP AL,DL      ; CURRENT, WALKERDAN BUYUK MU
JB YAZ         ; EGER BUYUKSE YAZ FONKSIYONUNA GIT
INC SI         ; WALKER DEGERINI 1 ARTTIR
CMP SI,09      ; WALKER SON ELEMAN MI
JBE J2         ; SON ELEMAN DEGILSE IC DONGUYU TEKRARLA
         
INC DI         ; WALKER = SON ELEMANSA DIS DONGU DEGISKENINI YANI CURRENT INDIS DEGERINI 1 ARTTIR
CMP DI,09      ; DIS DONGU DEGISKENI YANI CURRENT ILE TUM SAYILARA BAKILDI MI
JB J1          ; BAKILMADIYSA DIS DONGUYU TEKRARLA
HLT            ; BAKILDIYSA BITIR


YAZ:
MOV CL,AL ; YEDEKLE
MOV AL,DL ; AL = DL YANI BAKILAN ELEMAN = EN KUCUK ELEMAN
MOV DL,CL ; DL = AL YANI EN KUCUK ELEMAN = BAKILAN ELAMAN

MOV CL ,[BX+SI]         ; YEDEKLE
MOV BYTE PTR [BX+SI],AL ; BAKILAN ELEMANIN ADRESI = EN KUCUK ELEMANIN ADRESI    
MOV BYTE PTR [BX+DI],CL ; EN KUCUK ELEMANIN ADRESI = BAKILAN ELEMANIN ADRESI



INC SI          ; IC DONGU DEGISKENINI YANI WALKERI 1 ARTTIR    
CMP SI,09       ; WALKER SON ELEMAN MI 
JBE J2          ; DEGILSE IC DONGUYU TEKRARLAMAYA DALLAN
JA J1           ; WALKER SON ELEMANSA DIS DONGUYU TEKRARLAMAYA DALLAN






